### ISSUE TITLE
navigation default is "false"

### ISSUE THREAD

**Issue by MhmodElwakeel** [thiagosf/skitter#30]
in "http://skitter-slider.net/options.html"
it is mentioned that "navigation default" is "true" actually it is "false" 
you can check it "skitter-master/dist/"
 through the minify file "jquery.skitter.min.js" 
or the original one "jquery.skitter.js"  in line 45 
"  // Navigation display
    navigation: false, "

![false](https://cloud.githubusercontent.com/assets/23407062/20227539/b806a8e8-a81a-11e6-98eb-20769d595c8c.png)

![true](https://cloud.githubusercontent.com/assets/23407062/20227711/803096f8-a81b-11e6-8e76-1355fd9847e3.png)

**Comment by thiagosf** [comment]
Fixed, thanks! 👍

**Comment by MhmodElwakeel** [comment]
what about the new version of jQuery ? 
when I tried to use it instead of "<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>" , found it isn't compatible with skitter 

another one maybe you it would be better if you mentioned  how to put the images of "navigation - pause - continue and the others "  in the right path in "How to install " 

anyone 'll do your instruction but 'll forget to copy the images to his project as it isn't mentioned 

thanks
