### ISSUE TITLE
Measurements don't include CSS

### ISSUE THREAD

**Issue by ukozdan** [thiagosf/skitter#36]
Elements, such as **_.label_skitter_**, seem to be measured using **_.width()_**; this does not allow for alternative styling that changes measurements, such as padding and margin. Changing any width and height measurements to **_.outerWidth()_** and **_.outerHeight()_** would make this great slider more versatile and customizable.

**Comment by thiagosf** [comment]
Thanks for your feedback, I'm going to change this.
