### ISSUE TITLE
Image links of animation "circles" and "hideBars" donot work

### ISSUE THREAD

**Issue by huuvinh2019** [thiagosf/skitter#39]
Hi,
When I tried to set the animation of "circles" and "hideBars", I can see that image links donot work. In other words, when I click on the image, it does not redirect me to the target link. 
However, other animations can still work properly, so I am wondering if this is a bug? 
And could you please show me how to make it work for animation "circles" and "hideBars"?

**Comment by thiagosf** [comment]
Hello! Thanks by feedback, I'll fix this and I'll notice you.
